import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import Footer from "@/components/Footer";


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['500', '700']
})


export const metadata: Metadata = {
  title: "Url Shortner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} font-poppins`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
